//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BakkalWebProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class satis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public satis()
        {
            this.satis_maddeleri = new HashSet<satis_maddeleri>();
        }
    
        public int satis_id { get; set; }
        public System.DateTime s_tarih { get; set; }
        public string s_durum { get; set; }
        public int kullanici_id { get; set; }
    
        public virtual kullanici kullanici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<satis_maddeleri> satis_maddeleri { get; set; }
    }
}
