//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BakkalWebProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class urun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public urun()
        {
            this.satis_maddeleri = new HashSet<satis_maddeleri>();
        }
    
        public int urun_id { get; set; }
        public string u_adi { get; set; }
        public string u_barkodu { get; set; }
        public Nullable<System.DateTime> u_uretim_tarihi { get; set; }
        public Nullable<System.DateTime> u_tuketim_tarihi { get; set; }
        public double u_fiyat { get; set; }
        public Nullable<double> u_agirlik { get; set; }
        public string u_rengi { get; set; }
        public int marka_id { get; set; }
        public int kategori_id { get; set; }
        public int stok_id { get; set; }
    
        public virtual kategori kategori { get; set; }
        public virtual marka marka { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<satis_maddeleri> satis_maddeleri { get; set; }
        public virtual stok stok { get; set; }
    }
}
